# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{semantic_naming}
  s.version = "2.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Hahn"]
  s.date = %q{2010-02-04}
  s.email = %q{hahn@netseven.it}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/ontology_graph/class_node.rb",
     "lib/ontology_graph/graph.rb",
     "lib/semantic_naming.rb",
     "lib/semantic_naming/default_namespaces.rb",
     "lib/semantic_naming/namespace.rb",
     "lib/semantic_naming/predicate.rb",
     "lib/semantic_naming/source_class.rb",
     "lib/semantic_naming/uri.rb"
  ]
  s.homepage = %q{http://talia.discovery-project.eu/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Semantic Naming Extensions for ActiveRDF, Talia and others}
  s.test_files = [
    "test/class_node_test.rb",
     "test/graph_test.rb",
     "test/namespace_test.rb",
     "test/predicate_test.rb",
     "test/source_class_test.rb",
     "test/uri_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
